### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by Rafid-009** [Rafid-009/Hacktober_fest_2020#21]
Submit your code for hacktober fest 2020. I have already finished mine.

**Comment by Nitish-web-nik** [comment]
I want to contribute, please assign this to me.

**Comment by Anurajeev** [comment]
i would like to contribute, could you assign me

**Comment by Rafid-009** [comment]
@Nitish-web-nik  @Anurajeev  sure... I have done this all for you guys.. I also want people to complete their Fest

**Comment by kshsh00** [comment]
Please assign me

**Comment by ferch5003** [comment]
I want to contribute to this one, please assign me

**Comment by sourabhjain9887** [comment]
I would like to contribute , please assign this to me.

**Comment by kiyominox** [comment]
I would like to be added please
