### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Rafid-009** [Rafid-009/Hacktober_fest_2020#3]
**Data Structures, Algorithms and various real life Coding implementations by various open-source contributors.**

**Comment by AbhinavGor** [comment]
I can give code for singly linked lists, queues and djikstra algorithm implementation. @Rafid-009

**Comment by solankidivyam** [comment]
I can help with data structures ie, Arrays, Linked Lists, Stacks, Queues, Graphs and maps as well. Please assign a issue to me

**Comment by Rafid-009** [comment]
@solankidivyam @AbhinavGor  you can add any kind of algorithms & data structure if it is contributed/explained in a beginner friendly way.
